name: algorit
favicon: null
layout_spectrum: 0.4000192414969206
typography_spectrum: 0.2746298520360142
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.6472220397554338
  lightness: 0.39440205111168325
  saturation: 0.10044979234226048
  rhythmicContrast: 0.19692627131007612
purpose: []
